name: Build - Android

#on: push
on: 
  workflow_dispatch: {}

jobs:

  build:
    name: Build SuperBlaster for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
          fail-fast: false
          matrix:
            targetPlatform:
              - Android
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    
    steps:    
    - name: Free Disk Space for Android
      if: matrix.targetPlatform == 'Android'
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
              
              
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

    - name: Git LFS Pull
      run: |
        git lfs pull
        git add .
        git reset --hard

    - uses: actions/cache@v3
      with:
        path: Library
        key: Library-build-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-build-${{ matrix.targetPlatform }}-
          Library-build-
          

    - name: Build Unity Project
      id: build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ matrix.targetPlatform }}
        androidExportType: "androidAppBundle"
        androidKeystoreName: user.keystore
        androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
        androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
        androidTargetSdkVersion: AndroidApiLevel30


    - name: Upload build output
      uses: actions/upload-artifact@v3
      if: github.event.action == 'published' || contains(github.event.inputs.workflow_mode, matrix.targetPlatform) || (contains(github.event.inputs.workflow_mode, 'Steam') && matrix.targetPlatform == 'StandaloneLinux64')
      with:
        name: cgs-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}



#    - name: Unity build standalone windows 64 
#      uses: game-ci/unity-builder@v2
#      env:
#        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#      with:
#        targetPlatform: StandaloneWindows64
#        buildName: SuperBlaster-windowsx64




